# Generated by Django 5.1.2 on 2024-11-09 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Plants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(max_length=150)),
                ('water_requirement', models.IntegerField()),
                ('fertillizer_requirement', models.IntegerField()),
                ('harvest', models.IntegerField()),
                ('informations', models.TextField()),
                ('image', models.ImageField(upload_to='photo/%y/%m/%d')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.categories')),
            ],
        ),
    ]
