# Generated by Django 5.1.2 on 2024-11-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='category_name',
            field=models.CharField(choices=[('frute', 'الفواكه'), ('vegetable', 'الخضار'), ('grain', 'الحبوب'), ('herbs', 'الاعشاب'), ('ornamental', 'الزينة')], max_length=100),
        ),
    ]
