# Generated by Django 5.1.2 on 2024-11-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_image', models.ImageField(upload_to='photo/%y/%m/%d')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8)),
                ('unite_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('product_state', models.BooleanField(default=True)),
            ],
        ),
    ]
