# Generated by Django 5.1.2 on 2024-11-10 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='type',
        ),
    ]
